Repository zeel-codder/Recursion-Hub, pull requests merged in 2021-10, with the labels that each got.

#2 String Creation code
  Saksham/String_Creation.cpp
Labels: hacktoberfest-accepted

#5 GCD_LCM
  Code/GCD_LCM.java
Labels: hacktoberfest-accepted

#4 Code/Factorial.java
  Code/Factorial.java
  README.md
Labels: hacktoberfest-accepted

#7 Create Palindrome.java
  Code/Palindrome.java
  README.md
Labels: hacktoberfest-accepted

#19 solved reversingArray.md in c++
  Code/reversingarray.md
Labels: hacktoberfest-accepted

#23 Binary Search
  Code/BinarySearch.md
Labels: hacktoberfest-accepted

#16 added print array elements using recursion
  Code/print-array-using-recursion.md
Labels: hacktoberfest-accepted

#25 Made the website Responsive
  template/index.html
Labels: hacktoberfest-accepted

#11 Added check if a string is a rotated palindrome or not question
  Code/Rotated_Palindrome_String.md
Labels: hacktoberfest-accepted

#27 change ui
  Code/N-queens.md
Labels: hacktoberfest-accepted

#29 Made some styling on web page
  package-lock.json
  package.json
  template/index.html
Labels: hacktoberfest-accepted

#31 Recursion - Delete kth node from Linked List in java
  Code/delete_kth_node_from_linkedList.md
Labels: hacktoberfest-accepted

#33 Added BinaryExponentiation
  Code/BinaryExponentiation.md
Labels: hacktoberfest-accepted

#34 Create Permutations.md
  Code/Permutations.md
Labels: hacktoberfest-accepted

#36 Added The File To Rotate the Array
  Code/ReverseTheArray.md
Labels: hacktoberfest-accepted

#41 Added Blanced Paranthesis File #1
  Code/BalancedParanthesis.md
Labels: hacktoberfest-accepted

#35 Merge Sort in JavaScript in a Recursive way
  .DS_Store
  Code/MergeSort.md
Labels: hacktoberfest-accepted

#46 Error solved
  Code/BalancedParanthesis.md
  package-lock.json
  package.json
  static/js/index.js
Labels: hacktoberfest-accepted

#47 Added a program which prints Subsequences of a string
  Code/Subsequences.md
Labels: hacktoberfest-accepted

#43 Recursively Reverse the Linked List
  Code/ReverseLinkedList.md
Labels: hacktoberfest-accepted

#48 Added Tower of Hanoi
  Code/TowerofHanoi.md
Labels: hacktoberfest-accepted

#49 Add files via upload
  Code/Product of 2 Numbers.md
Labels: hacktoberfest-accepted

#13 Added recursive Insertion Sort
  Code/InsertionSort.md
  README.md
Labels: bug, hacktoberfest-accepted

#54 Added Ternary Search
  Code/RecursiveTernarySearch.md
Labels: hacktoberfest-accepted

#52 Max_product_subset.cpp
  Code/Max_Product_Subset.md
Labels: hacktoberfest-accepted, newproblem

#55 Added program that converts Decimal to Binary
  Code/Decimal to Binary Conversion.md
Labels: hacktoberfest-accepted

#56 program of palindrome
  Code/palindrome program
Labels: hacktoberfest-accepted

#53 Added shortest path in maze problem
  Code/Shortest_path_in_maze.md
Labels: hacktoberfest-accepted, New

#57 Two Sum Leetcode
  Code/TwoSum.md
Labels: hacktoberfest-accepted

#58 code using recursion
  Code/First-Index-of-Number.md
  Code/Power-of-number.md
Labels: hacktoberfest-accepted

#60 Source to destination using recursion with two moves
  Code/SourceToDestination.md
Labels: hacktoberfest-accepted, New

#88 add_digits.md added
  Code/add_digits.md
Labels: hacktoberfest-accepted

#87 update twosum.md
  Code/TwoSum.md
Labels: hacktoberfest-accepted
